# Generated by Django 3.2.2 on 2022-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='dominant_hex',
            field=models.CharField(default='#000000', max_length=250),
        ),
    ]
