# Generated by Django 3.2.2 on 2022-04-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='dominant_rgb',
            field=models.CharField(default='rgb(255,255,255)', max_length=250),
        ),
    ]
