# Generated by Django 3.2.2 on 2022-02-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagegalleryimage',
            name='dominantColor',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
